title: Resource site for ISO/TC 154
title_html: Resource site for&nbsp;ISO/TC&nbsp;154

email: open.source@ribose.com

description: >-
  Resource site for ISO/TC 154

tagline: ""

baseurl: ""
url: "https://www.isotc154.org"

theme: jekyll-theme-isotc211

social:
  links:
    - url: https://twitter.com/ISOTC154
    - url: https://github.com/ISO-TC154
    - url: https://www.facebook.com/groups/236669159734679/
    - url: https://www.linkedin.com/groups/4222374

footer_nav:
  - url: https://committee.iso.org/home/tc154
    title: Committee Site

powered_by:
  url: https://open.ribose.com
  title: Ribose
  logo_path: /assets/logo-ribose.svg

nav:
  home:
    url: /
    title: Home
  about:
    url: /about
    title: About ISO/TC 154
  faq:
    url: /faq
    title: FAQ
  standards:
    url: /standards
    title: Standards

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - deploy.sh
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/

header_pages:
  - index.adoc
  - about.adoc
  - contact.adoc
  - faq.adoc
  - minutes.adoc
  - projects.adoc
  - standards.adoc

