title: ISO/TC 154 Committee site
title_html: ISO/TC&nbsp;154

email: open.source@ribose.com

committee:
  id: 154
  name: Processes, data elements and documents in commerce, industry and administration
  link: https://committee.iso.org/home/tc154

description: >-
  ISO/TC 154 Committee site
  Processes, data elements and documents in commerce, industry and administration

tagline: >-
  Resources

baseurl: ""
url: "https://www.isotc154.org"

theme: jekyll-theme-isotc211

social:
  links:
    - url: https://twitter.com/ISOTC154
    - url: https://github.com/ISO-TC154
    - url: https://www.facebook.com/groups/236669159734679/
    - url: https://www.linkedin.com/groups/4222374

footer_nav:
  - url: https://www.gefeg.com/jswg/
    title: JWG 1 Site
  # - url: https://committee.iso.org/home/tc154
  #   title: Committee Site

powered_by:
  url: https://open.ribose.com
  title: Ribose
  logo_path: /assets/logo-ribose.svg

collections:
  minutes:
    output: true
    permalink: /:collection/:date/
  standards:
    output: true
    permalink: /:collection/:name/
  groups:
    output: true
    permalink: /about/:name/

defaults:
  - scope:
      path: ""
      type: "minutes"
    values:
      layout: post
  - scope:
      path: ""
      type: "standards"
    values:
      layout: post
  - scope:
      path: ""
      type: "projects"
    values:
      layout: post
  - scope:
      path: ""
      type: "groups"
    values:
      layout: post

nav:
  home:
    url: /
    title: Home
  about:
    url: /about
    title: About ISO/TC 154
  faq:
    url: /faq
    title: FAQ
  standards:
    url: /standards
    title: Standards
  projects:
    url: /projects
    title: Projects
  sdmr:
    url: /procedures/sdmr
    title: JWG 1 SDMR

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - deploy.sh
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/

header_pages:
  - index.adoc
  - about.adoc
  - contact.adoc
  - faq.adoc
  - minutes.adoc
  - projects.adoc
  - standards.adoc

