title: ISO/TC 154 Committee site
title_html: ISO/TC&nbsp;154

email: open.source@ribose.com

description: >-
  ISO/TC 154 Committee site
  Processes, data elements and documents in commerce, industry and administration

tagline: >-
  Official site

baseurl: ""
url: "https://www.isotc154.org"

markdown: kramdown

excerpt_separator: "// more"

social:
  links:
    - url: https://twitter.com/ISOTC154
    - url: https://github.com/ISO-TC154
    - url: https://www.facebook.com/groups/236669159734679/
    - url: https://www.linkedin.com/groups/4222374

footer_nav_items:
  - home
  - sitemap
  - news
  - contact

primary_nav_items:
  - about
  - projects
  - standards
  - minutes
  - faq
  - meetings

collections:
  pages:
    output: true
    permalink: /:name/
  minutes:
    output: true
    permalink: /:collection/:date/
  standards:
    output: true
    permalink: /:collection/:name/
  projects:
    output: true
    permalink: /:collection/:name/
  procedures:
    output: true
    permalink: /:collection/:name/
  groups:
    output: true
    group-id: :name
  members:
    output: true
    member-id: :name

defaults:
  - scope:
      path: "faq"
    values:
      layout: faq
  - scope:
      path: ""
      type: minutes
    values:
      layout: minutes
  - scope:
      path: ""
      type: standards
    values:
      layout: standard
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: procedures
    values:
      layout: procedures
  - scope:
      path: ""
      type: groups
    values:
      layout: group

nav:
  about:
    url: /about/
    title: About
  faq:
    url: /faq/
    title: FAQ
  standards:
    url: /standards/
    title: Standards
  projects:
    url: /projects/
    title: Projects
  minutes:
    url: /minutes/
    title: Minutes
  meetings:
    url: /meetings/
    title: Meetings

  home:
    url: /
    title: Home
  sitemap:
    url: /sitemap/
    title: Sitemap
  news:
    url: /news/
    title: News
  contact:
    url: /contact
    title: Contact

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - deploy.sh
  - node_modules
  - vendor
  - .sass-cache/
